---
title: "Experience"
permalink: /experience/
output: 
  html_document
---

### The Center for Innovative Design and Analysis (CIDA)
#### Research Associate, July 2021 - present

In my current faculty position at the Colorado School of Public Health, my research focus lies in collaborative work. I am the manager of CIDA's Consulting Center, where I oversee the intake and assignment of internal and external research projects requiring statistical expertise. In this role, I also supervise masters level statisticians and students, helping them develop their skills as collaborative statisticians working with real-life clients. Within the Department of Internal Medicine's Division of Gastroenterology and Hepatology, I lead the biostatistical support for the Gastroenterology Outcomes Research Group (GORG) as well as serve as the lead biostatistician on a grant comparing two sampling protocols for Barrett's Esophagus. I also serve as an analyst on two grants through the Department of Family Medicine, one comparing different modes of medication assisted treatment induction for opioid misuse disorder([The HOMER Study](https://medschool.cuanschutz.edu/homer)) and another assessing the impact of a program empowering former smokers to help others in their network quit. 


### The University of Virginia (UVA) Department of Public Health Sciences
#### Postdoctoral Research Associate, September 2019 - June 2021

As a postdoctoral research associate under the mentorship of Dr. Sarah Ratcliffe, I continued my research modeling and simulating survey dropout while also focusing on the application and extension of functional data analysis methods. In this position, I provided statistical support to researchers in the UVA Health System primarily through the Center for Advanced Medical Analytics and also to researchers at the University of Pennsylvania School of Nursing. My collaborative projects included developing an early warning metric for respiratory distress and analyzing shared decision-making patterns in cancer patients participating in clinical trials. 




### Virginia Commonwealth University (VCU) Department of Family Medicine and Population Health
#### Graduate Research Assistant, January 2015 - May 2019

As a member of the qualitative team within the Department of Family Medicine Research Team led by Dr. Alex Krist, I consulted and collaborated on a large range of projects, from quantifying missed well-child care visit, to summarizing characteristics of providers prescribing and patients receiving opioid prescriptions, to analyzing uptake of screening guidelines in primary care. I collaborated at each stage of the research process, gaining experience in project planning, grant writing, data management, analysis, and manuscript/poster preparation. In this role, I gained skills in SAS, SQL, and R. Hierarchical, longitudinal, and survival analyses characterize the majority of my analytical contributions while I also prepared figures and maps to visually accompany these results. 



### VCU Department of Biostatistics
#### Teaching Assistant, August 2014 - December 2014

As a teaching assistant for the Graduate Research Methods I course, I held office hours to help students understand course material and successfully complete assignments. I was also responsible for grading assignments.

